data_path: data
dataset: steam_data
model: BERT4Rec
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: is_recommended
TIME_FIELD: timestamp
# show_progress: false
load_col:
    inter: [user_id, item_id, is_recommended, timestamp]
    item: [item_id, item_emb]
neg_sampling: null
train_neg_sample_args: null
selected_features: [item_emb]
metrics: [Recall, MRR, NDCG]
train_batch_size: 256
eval_batch_size: 256
inner_size: 256
epochs: 1
loss_type: CE
pooling_mode: sum
hidden_act: 'gelu'
layer_norm_eps: 1e-12
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.5
initializer_range: 0.02

eval_args:
    split: {'RS': [0.8, 0.2, 0]}
    group_by: user
    order: TO
    mode: full
valid_metric: Recall@10
gpu_id: 5